-- phpMyAdmin SQL Dump
-- version 4.9.5
-- https://www.phpmyadmin.net/
--
-- Host: mysql16j15.db.hostpoint.internal
-- Generation Time: Apr 10, 2020 at 03:46 PM
-- Server version: 10.1.44-MariaDB
-- PHP Version: 7.2.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `escortgi_flowerspower`
--

-- --------------------------------------------------------

--
-- Table structure for table `country`
--

CREATE TABLE `country` (
  `idCountry` int(11) NOT NULL,
  `name` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `nameFr` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `languageCode` varchar(4) COLLATE utf8_unicode_ci NOT NULL,
  `language` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `code` varchar(4) COLLATE utf8_unicode_ci NOT NULL,
  `capitalCity` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `currency` varchar(64) COLLATE utf8_unicode_ci NOT NULL,
  `currencyLink` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `localTime` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `map` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `weather` mediumtext COLLATE utf8_unicode_ci NOT NULL,
  `zonesIATA` varchar(255) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `country`
--

INSERT INTO `country` (`idCountry`, `name`, `nameFr`, `languageCode`, `language`, `code`, `capitalCity`, `currency`, `currencyLink`, `localTime`, `map`, `weather`, `zonesIATA`) VALUES
(1, 'Afghanistan', 'Afghanistan', '', '', 'AF', '0', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Afghanistan_Kabul\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '0', '0', '3'),
(2, 'Albania', 'Albanie', '', '', 'AL', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Albania_Tirane\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', '2'),
(3, 'Algeria', 'Algerie', '', '', 'DZ', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Algeria_Algiers\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', '2'),
(4, 'American Samoa', 'Samoa am&eacute;ricaines', '', '', 'AS', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"AmericanSamoa_PagoPago\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', '3'),
(5, 'Andorra', 'Andorre', '', '', 'AD', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Andorra_AndorraLaVella\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', '2'),
(6, 'Angola', 'Angola', '', '', 'AO', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Angola_Luanda\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', '2'),
(7, 'Anguilla', 'Anguilla', '', '', 'AI', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Anguilla_CrocusHill\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', '1'),
(8, 'Antigua and Barbuda', 'Antigua et Barbuda', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"AntiguaandBarbuda_StJohns\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(9, 'Argentina', 'Argentine', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Argentina_BahiaBlanca\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(10, 'Armenia', 'Arm&eacute;nie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Armenia_Yerevan\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(11, 'Aruba', 'Aruba', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Aruba_Oranjestad\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(12, 'Australia', 'Australie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Australia_Melbourne\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(13, 'Austria', 'Autriche', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Austria_Salzburg\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(14, 'Azerbaijan', 'Azerba&iuml;djan', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Azerbaijan_Baku\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(15, 'Bahrain', 'Bahre&iuml;n', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Bahrain_Manama\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(16, 'Bangladesh', 'Bangladesh', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Bangladesh_Dhaka\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(17, 'Barbados', 'Barbade', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Barbados_Bridgetown\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(18, 'Belarus', 'B&eacute;larus', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Belarus_Minsk\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(19, 'Belgium', 'Belgique', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Belgium_Brussels\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(20, 'Belize', 'Belize', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Belize_BelizeCity\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(21, 'Benin', 'B&eacute;nin', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Benin_Cotonou\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(22, 'Bermuda', 'Bermudes', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Bermuda_Hamilton\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(23, 'Bhutan', 'Bhoutan', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Bhutan_Thimphu\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(24, 'Bolivia', 'Bolivie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Bolivia_LaPaz\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(25, 'Bosnia and Herzegovina', 'Bosnie-Herz&eacute;govine', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"BosniaandHerzegovina_Sarajevo\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(26, 'Bostswana', 'Bostswana', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Botswana_Gaborone\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(27, 'Bouvet Island', '&Icirc;le Bouvet', '', '', '', '', '', '', '', '', '', ''),
(28, 'Brazil', 'Br&eacute;sil', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Brazil_RiodeJaneiro\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(29, 'British Indian Ocean Territory', 'Territoire britannique de l&rsquo;oc&eacute;an Indien', '', '', '', '', '', '', '', '', '', ''),
(30, 'British Virgin Islands', '&Icirc;les Vierges britanniques', '', '', '', '', '', '', '', '', '', ''),
(31, 'Brunei', 'Brun&eacute;i Darussalam', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"BruneiDarussalam_BandarSeriBegawan\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(32, 'Bulgaria', 'Bulgarie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Bulgaria_Sofia\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(33, 'Burkina Faso', 'Burkina Faso', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"BurkinaFaso_Ouagadougou\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(34, 'Burma', 'Birmanie', '', '', '', '', '', '', '', '', '', ''),
(35, 'Burundi', 'Burundi', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Burundi_Bujumbura\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(36, 'Cambodia', 'Cambodge', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Cambodia_PhnomPenh\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(37, 'Cameroon', 'Cameroun', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Cameroon_Yaounde\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(38, 'Canada', 'Canada', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Canada_Vancouver\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(39, 'Cape Verde', 'Cap-Vert', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"CapeVerde_Praia\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(40, 'Cayman Islands', '&Icirc;les Ca&iuml;mans', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"CaymanIslands_GeorgeTown\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(41, 'Central African Republic', 'R&eacute;publique centrafricaine', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"CentralAfricanRepublic_Bangui\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(42, 'Chad', 'Tchad', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Chad_NDjamena\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(43, 'Chile', 'Chili', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Chile_Santiago\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(44, 'China', 'Chine', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"China_Beijing\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(45, 'Christmas Islands', 'Iles Christmas', '', '', '', '', '', '', '', '', '', ''),
(46, 'Cocos (Keeling) Islands', '&Icirc;les des Cocos', '', '', '', '', '', '', '', '', '', ''),
(47, 'Colombia', 'Colombie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Colombia_Bogota\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(48, 'Comoros', 'Comores', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Comoros_Moroni\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(49, 'Cook Islands', '&Icirc;les Cook', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"CookIslands_Rarotonga\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(50, 'Costa Rica', 'Costa Rica', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"CostaRica_SanJose\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(51, 'Cote d\'Ivoire', 'C&ocirc;te d&rsquo;Ivoire', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"CoteDIvoire_Abidjan\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(52, 'Croatia', 'Croatie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Croatia_Zagreb\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(53, 'Cuba', 'Cuba', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Cuba_Havana\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(54, 'Cyprus', 'Chypre', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Cyprus_Nicosia\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(55, 'Czech Republic', 'R&eacute;publique tch&egrave;que', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"CzechRepublic_Prague\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(56, 'Democratic Republic of the Congo', 'R&eacute;publique d&eacute;mocratique du Congo', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"CongoDemocraticRepublic_Kananga\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(57, 'Denmark', 'Danemark', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Denmark_Copenhagen\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(58, 'Djibouti', 'Djibouti', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Djibouti_Djibouti\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(59, 'Dominica', 'Dominique', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Dominican_SantoDomingo\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(60, 'Dominican Republic', 'R&eacute;publique dominicaine', '', '', '', '', '', '', '', '', '', ''),
(61, 'Ecuador', '&Eacute;quateur', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Ecuador_Quito\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(62, 'Egypt', '&Eacute;gypte', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Egypt_Cairo\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(63, 'El Salvador', 'El Salvador', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"ElSalvador_SanSalvador\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(64, 'Equatorial Guinea', 'Guin&eacute;e &eacute;quatoriale', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"EquatorialGuinea_Malabo\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(65, 'Eritrea', '&Eacute;rythr&eacute;e', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Eritrea_Asmara\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(66, 'Estonia', 'Estonie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Estonia_Tallinn\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(67, 'Ethiopia', '&Eacute;thiopie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Ethiopia_AddisAbaba\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(68, 'Falkland Islands (Islas Malvinas)', 'Iles Falkland (Malouines)', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"FalklandIslands_PortStanley\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(69, 'Faroe Islands', '&Icirc;les F&eacute;ro&eacute;', '', '', '', '', '', '', '', '', '', ''),
(70, 'Fiji', 'Fidji', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Fiji_Suva\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(71, 'Finland', 'Finlande', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Finland_Helsinki\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(72, 'France', 'France', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"France_Paris\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(73, 'French Polynesia', 'Polyn&eacute;sie Fran&ccedil;aise', '', '', '', '', '', '', '', '', '', ''),
(74, 'Gabon', 'Gabon', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Gabon_Libreville\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(75, 'Georgia', 'G&eacute;orgie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Georgia_Tbilisi\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(76, 'Germany', 'Allemagne', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Germany_Berlin\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(77, 'Ghana', 'Ghana', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Ghana_Accra\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(78, 'Gibraltar', 'Gibraltar', '', '', '', '', '', '', '', '', '', ''),
(79, 'Greece', 'Gr&egrave;ce', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Greece_Athens\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(80, 'Greenland', 'Groenland', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Greenland_Nuuk\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(81, 'Grenada', 'Grenade', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Grenada_SaintGeorges\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(82, 'Guam', 'Guam', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Guam_Hagatna\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(83, 'Guatemala', 'Guatemala', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Guatemala_GuatemalaCity\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(84, 'Guernsey', 'Guernesey', '', '', '', '', '', '', '', '', '', ''),
(85, 'Guinea', 'Guin&eacute;e', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Guatemala_GuatemalaCity\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(86, 'Guinea-Blissau', 'Guin&eacute;e-Blissau', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Guinea-Bissau_Bissau\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(87, 'Guyana', 'Guyana', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Guyana_Georgetown\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(88, 'Haiti', 'Ha&iuml;ti', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Haiti_Port-au-Prince\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(89, 'Holy See (Vatican City)', 'Saint-Si&egrave;ge (Vatican)', '', '', '', '', '', '', '', '', '', ''),
(90, 'Honduras', 'Honduras', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Honduras_Tegucigalpa\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(91, 'Hong Kong', 'Hong Kong', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"HongKong_HongKong\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(92, 'Hungary', 'Hongrie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Hungary_Budapest\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(93, 'Iceland', 'Islande', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Iceland_Reykjavik\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(94, 'India', 'Inde', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"India_NewDelhi\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(95, 'Indonesia', 'Indon&eacute;sie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Indonesia_Ambon\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(96, 'Iran', 'Iran', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Iran_Tehran\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(97, 'Iraq', 'Iraq', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Iraq_Baghdad\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(98, 'Ireland', 'Irlande', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Ireland_Dublin\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(99, 'Isle of Man', 'Ile de Man', '', '', '', '', '', '', '', '', '', ''),
(100, 'Israel', 'Isra&euml;l', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Israel_Jerusalem\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(101, 'Italy', 'Italie', 'IT', 'Italien', 'IT', 'Roma', 'Euro', 'http://www.xe.com/ucc/convert.cgi?template=fr&Amount=1&From=CHF&To=EUR', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Italy_Milan\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', 'http://maps.google.ch/maps?f=q&source=s_q&hl=fr&geocode=&q=italy&aq=&sll=46.362093,9.036255&sspn=6.194073,14.27124&ie=UTF8&hq=&hnear=Italie&t=h&z=6', '', '2'),
(102, 'Jamaica', 'Jama&iuml;que', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Jamaica_Kingston\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(103, 'Japan', 'Japon', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Japan_Kyoto\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(104, 'Jordan', 'Jordanie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Jordan_Amman\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(105, 'Kazahstan', 'Kazahstan', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Kazakhstan_Aktau\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(106, 'Kenya', 'Kenya', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Kenya_Nairobi\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(107, 'Kiribati', 'Kiribati', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Kiribati_Tarawa\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(108, 'Kosovo', 'Kosovo', '', '', '', '', '', '', '', '', '', ''),
(109, 'Kuwait', 'Kowe&iuml;t', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Kuwait_KuwaitCity\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(110, 'Kyrgyzstan', 'Kirghizistan', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Kyrgyzstan_Bishkek\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(111, 'Laos', 'Laos', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"LaoPeoplesDemocratic_Vientiane\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(112, 'Latvia', 'Lettonie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Latvia_Riga\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(113, 'Lebanon', 'Liban', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Lebanon_Beirut\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(114, 'Lesotho', 'Lesotho', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Lesotho_Maseru\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(115, 'Liberia', 'Lib&eacute;ria', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Liberia_Monrovia\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(116, 'Libya', 'Libye', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"LibyanArabJamahiriya_Tripoli\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(117, 'Liechtenstein', 'Liechtenstein', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Liechtenstein_Vaduz\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(118, 'Lithuania', 'Lituanie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Lithuania_Vilnius\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(119, 'Luxembourg', 'Luxembourg', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Luxembourg_Luxembourg\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(120, 'Macau', 'Macao', '', '', '', '', '', '', '', '', '', ''),
(121, 'Macedonia', 'Mac&eacute;doine', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"MacedoniaTheFormer_Skopje\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(122, 'Madagascar', 'Madagascar', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Madagascar_Antananarivo\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(123, 'Malawi', 'Malawi', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Malawi_Lilongwe\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(124, 'Malaysia', 'Malaisie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Malaysia_KualaLumpur\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(125, 'Maldives', 'Maldives', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Maldives_Male\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(126, 'Mali', 'Mali', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Mali_Bamako\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(127, 'Malta', 'Malte', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Malta_Valletta\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(128, 'Marschal Islands', '&Icirc;les Marschal', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"MarshallIslands_Majuro\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(129, 'Mauritania', 'Mauritanie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Mauritania_Nouakchott\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(130, 'Mauritius', 'Maurice', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Mauritius_PortLouis\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(131, 'Mayotte', 'Mayotte', '', '', '', '', '', '', '', '', '', ''),
(132, 'Mexico', 'Mexique', '', '', '', '', '', '', '', '', '', ''),
(133, 'Micronesia', 'Micron&eacute;sie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"MicronesiaFederated_Kolonia\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(134, 'Moldova', 'Moldavie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"MoldovaRepublicof_Chisinau\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(135, 'Monaco', 'Monaco', '', '', '', '', '', '', '', '', '', ''),
(136, 'Mongolia', 'Mongolie', '', '', '', '', '', '', '', '', '', ''),
(137, 'Montenegro', 'Mont&eacute;n&eacute;gro', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Montenegro_Podgorica\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(138, 'Montserrat', 'Montserrat', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `country` (`idCountry`, `name`, `nameFr`, `languageCode`, `language`, `code`, `capitalCity`, `currency`, `currencyLink`, `localTime`, `map`, `weather`, `zonesIATA`) VALUES
(139, 'Morocco', 'Maroc', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Morocco_Casablanca\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(140, 'Mozambique', 'Mozambique', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Mozambique_Maputo\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(141, 'Namibia', 'Namibie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Namibia_Windhoek\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(142, 'Nauru', 'Nauru', '', '', '', '', '', '', '', '', '', ''),
(143, 'Nepal', 'Nepal', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Nepal_Kathmandu\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(144, 'Netherlands Anthilles', 'Pays-Bas Anthilles', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"NetherlandsAntilles_Kralendijk\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(145, 'Netherlands', 'Pays-Bas', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Netherlands_Amsterdam\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(146, 'New Zealand', 'Nouvelle-Z&eacute;lande', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"NewZealand_Auckland\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(147, 'Nicaragua', 'Nicaragua', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Nicaragua_Managua\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(148, 'Niger', 'Niger', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Niger_Niamey\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(149, 'Nigeria', 'Nig&eacute;ria', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Nigeria_Lagos\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(150, 'Niue', 'Niue', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Niue_Alofi\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(151, 'Norfolk Island', '&Icirc;le Norfolk', '', '', '', '', '', '', '', '', '', ''),
(152, 'North Korea', 'Cor&eacute;e du Nord', '', '', '', '', '', '', '', '', '', ''),
(153, 'Northern Mariana Islands', '&Icirc;les Mariannes du Nord', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"NorthernMarianaIslands_Saipan\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(154, 'Norway', 'Norv&egrave;ge', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Norway_Oslo\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(155, 'Oman', 'Oman', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Oman_Muscat\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(156, 'Pakistan', 'Pakistan', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Pakistan_Islamabad\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(157, 'Palau', 'Palaos', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Palau_Koror\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(158, 'Panama', 'Panama', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Panama_PanamaCity\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(159, 'Papua New Guinea', 'Papouasie-Nouvelle-Guin&eacute;e', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"PapuaNewGuinea_PortMoresby\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(160, 'Paraguay', 'Paraguay', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Paraguay_Asuncion\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(161, 'Peru', 'P&eacute;rou', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Peru_Lima\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(162, 'Philippines', 'Philippines', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Philippines_Manila\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(163, 'Pitcairn Islands', '&Icirc;les Pitcairn', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Pitcairn_Adamstown\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(164, 'Poland', 'Pologne', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Poland_Warsaw\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(165, 'Portugal', 'Portugal', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Portugal_Funchal\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(166, 'Puerto Rico', 'Porto Rico', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"PuertoRico_SanJuan\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(167, 'Quatar', 'Quatar', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Qatar_Doha\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(168, 'Republic of the Congo', 'R&eacute;publique du Congo', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"CongoDemocraticRepublic_Kananga\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(169, 'Romania', 'Roumanie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Romania_Bucharest\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(170, 'Russia', 'Russie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Russia_Moscow\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(171, 'Rwanda', 'Rwanda', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Rwanda_Kigali\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(172, 'Saint Helena', 'Sainte-H&eacute;l&egrave;ne', '', '', '', '', '', '', '', '', '', ''),
(173, 'Saint Kitts and Nevis', 'Saint Kitts et Nevis', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"SaintKittsandNevis_Basseterre\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(174, 'Saint Lucia', 'Sainte-Lucie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"SaintLucia_Castries\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(175, 'Saint Pierre and Miquelon', 'Saint-Pierre-et-Miquelon', '', '', '', '', '', '', '', '', '', ''),
(176, 'Saint Vincent', 'Saint-Vincent', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"SaintVincentandThe_Kingstown\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(177, 'Samoa', 'Samoa', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Samoa_Apia\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(178, 'San Marino', 'Saint-Marin', '', '', '', '', '', '', '', '', '', ''),
(179, 'Sao Tome and Principe', 'S&atilde;o Tom&eacute; et Pr&iacute;ncipe', '', '', '', '', '', '', '', '', '', ''),
(180, 'Saudi Arabia', 'Arabie Saoudite', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"SaudiArabia_Riyadh\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(181, 'Senegal', 'Senegal', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"SaudiArabia_Riyadh\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(182, 'Seychelles', 'Seychelles', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Seychelles_Victoria\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(183, 'Sierra Leone', 'Sierra Leone', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"SierraLeone_Freetown\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(184, 'Singapore', 'Singapour', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Singapore_SingaporeCity\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(185, 'Slovakia', 'Slovaquie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Slovakia_Bratislava\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(186, 'Slovenia', 'Slov&eacute;nie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Slovenia_Ljubljana\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(187, 'Solomon Islands', '&Icirc;les Salomon', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"SolomonIslands_Honiara\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(188, 'Somalia', 'Somalie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Somalia_Mogadishu\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(189, 'South Africa', 'Afrique du Sud', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"SouthAfrica_Johannesburg\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(190, 'South Georgia and the South Sandwitch Islands', 'G&eacute;orgie du Sud et Iles Sandwich du Sud', '', '', '', '', '', '', '', '', '', ''),
(191, 'South Korea', 'Cor&eacute;e du Sud', '', '', '', '', '', '', '', '', '', ''),
(192, 'Spain', 'Espagne', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Spain_Barcelona\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(193, 'Sri Lanka', 'Sri Lanka', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"SriLanka_Colombo\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(194, 'Sudan', 'Soudan', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Sudan_Khartoum\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(195, 'Suriname', 'Suriname', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Suriname_Paramaribo\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(196, 'Swaziland', 'Swaziland', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Swaziland_Mbabane\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(197, 'Sweden', 'Su&egrave;de', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Sweden_Stockholm\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(198, 'Switzerland', 'Suisse', 'FR, ', 'FranÃ§ais, Italien, Allemand', 'CH', 'Bern', 'CHF', 'http://www.xe.com/ucc/convert.cgi?template=fr&Amount=1&From=EUR&To=CHF', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Switzerland_Bern\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', 'http://maps.google.ch/maps?hl=fr&doflg=ptk&ie=UTF8&ll=46.705969,8.453979&spn=3.077494,7.13562&t=h&z=8', '', '2'),
(199, 'Syria', 'Syrie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"SyrianArabRepublic_Damascus\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(200, 'Taiwan', 'Ta&iuml;wan', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Taiwan_Taipei\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(201, 'Tajikistan', 'Tadjikistan', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Tajikistan_Dushanbe\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(202, 'Tanzania', 'Tanzanie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Tanzania_DaresSalaam\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(203, 'Thailand', 'Tha&iuml;lande', '', 'Thailandais', 'TH', 'Bangkok', 'THB', 'http://www.xe.com/ucc/convert.cgi?template=fr&Amount=1&From=CHF&To=THB', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Thailand_Bangkok\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', 'http://maps.google.ch/maps?f=q&source=s_q&hl=fr&geocode=&q=Tha%C3%AFlande&aq=3&sll=15.623037,103.051758&sspn=17.227359,28.54248&ie=UTF8&hq=&hnear=Tha%C3%AFlande&ll=15.876809,100.986328&spn=17.206161,28.54248&t=h&z=6', '', '3'),
(204, 'the Bahamas', 'les Bahamas', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Bahamas_Nassau\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(205, 'the Gambia', 'la Gambie', '', '', '', '', '', '', '', '', '', ''),
(206, 'Tibet', 'Tibet', '', '', '', '', '', '', '', '', '', ''),
(207, 'Timor-Leste', 'Timor-Leste', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Timor-Leste_Dili\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(208, 'Togo', 'Togo', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Togo_Lome\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(209, 'Tonga', 'Tonga', '', '', '', '', '', '', '', '', '', ''),
(210, 'Trinidad and Tobago', 'Trinidad et Tobago', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Trinidadand_Port-of-Spain\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(211, 'Tunisia', 'Tunisie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Tunisia_Tunis\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(212, 'Turkey', 'Turquie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Turkey_Ankara\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(213, 'Turkmenistan', 'Turkm&eacute;nistan', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Turkmenistan_Ashgabat\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(214, 'Turks and Caicos Islands', '&Icirc;les Turks et Ca&iuml;ques', '', '', '', '', '', '', '', '', '', ''),
(215, 'Tuvalu', 'Tuvalu', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Tuvalu_Funafuti\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(216, 'Uganda', 'Ouganda', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Uganda_Kampala\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(217, 'Ukraine', 'Ukraine', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Ukraine_Kiev\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(218, 'United Arab Emirates', '&Eacute;mirats arabes unis', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"UnitedArabEmirates_AbuDhabi\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(219, 'United Kingdom', 'Royaume-Uni', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"UnitedKingdom_London\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(220, 'United States', '&Eacute;tats-Unis', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"USA_NewYork\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(221, 'Uruguay', 'Uruguay', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Uruguay_Montevideo\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(222, 'Uzbekistan', 'Ouzb&eacute;kistan', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Uzbekistan_Tashkent\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(223, 'Vanuatu', 'Vanuatu', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Vanuatu_Port-Vila\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(224, 'Venezuela', 'Venezuela', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Venezuela_Caracas\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(225, 'Vietnam', 'Vietnam', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"VietNam_Hanoi\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(226, 'Virgin Islands', 'Iles Vierges', '', '', '', '', '', '', '', '', '', ''),
(227, 'Wallis and Futuna', 'Wallis et Futuna', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"WallisandFutuna_Mata-Utu\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(228, 'Yemen', 'Y&eacute;men', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Yemen_Sanaa\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(229, 'Zambia', 'Zambie', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Zambia_Lusaka\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(230, 'Zimbabwe', 'Zimbabwe', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"Zimbabwe_Harare\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(231, 'Akrotiri', 'Akrotiri', '', '', '', '', '', '', '', '', '', ''),
(232, 'Baker Island', '&Icirc;les Baker', '', '', '', '', '', '', '', '', '', ''),
(233, 'Clipperton Island', '&Icirc;le Clipperton', '', '', '', '', '', '', '', '', '', ''),
(234, 'Coral Sea Islands', '&Icirc;sles de la Mer de Corail', '', '', '', '', '', '', '', '', '', ''),
(235, 'Dhekelia', 'Dhekelia', '', '', '', '', '', '', '', '', '', ''),
(236, 'French Southern and Antarctic Lands', 'Territoires fran&ccedil;ais du Sud et de l&rsquo;Antarctique', '', '', '', '', '', '', '', '', '', ''),
(237, 'Heard Island and McDonald Islands', '&Icirc;les Heard et MacDonald', '', '', '', '', '', '', '', '', '', ''),
(238, 'Howland Island', '&Icirc;le Howland', '', '', '', '', '', '', '', '', '', ''),
(239, 'Jan Mayen', 'Jan Mayen', '', '', '', '', '', '', '', '', '', ''),
(240, 'Jarvis Island', '&Icirc;le Jarvis', '', '', '', '', '', '', '', '', '', ''),
(241, 'Johnston Atoll', 'Atoll de Johnston', '', '', '', '', '', '', '', '', '', ''),
(242, 'Jersey', 'Jersey', '', '', '', '', '', '', '', '', '', ''),
(243, 'Kingman Reef', 'R&eacute;cif Kingman', '', '', '', '', '', '', '', '', '', ''),
(244, 'Midway Islands', '&Icirc;les Midway', '', '', '', '', '', '', '', '', '', ''),
(245, 'Navassa Island', 'Ile Navassa', '', '', '', '', '', '', '', '', '', ''),
(246, 'New Caledonia', 'Nouvelle-Cal&eacute;donie', '', '', '', '', '', '', '', '', '', ''),
(247, 'Palmyra Atoll', 'Atoll de Palmyra', '', '', '', '', '', '', '', '', '', ''),
(248, 'Saint Barthelemy', 'Saint-Barth&eacute;l&eacute;my', '', '', '', '', '', '', '', '', '', ''),
(249, 'Saint Martin', 'Saint-Martin', '', '', '', '', '', '', '<script src=\"http://www.clocklink.com/embed.js\"></script><script type=\"text/javascript\" language=\"JavaScript\">obj=new Object;obj.clockfile=\"5001p-blue.swf\";obj.TimeZone=\"SaintMartin_Marigot\";obj.width=300;obj.height=25;obj.Place=\"Local Time\";obj.DateFormat=\"DD-mm-YYYY\";obj.wmode=\"transparent\";showClock(obj);</script>', '', '', ''),
(250, 'Serbia', 'Serbie', '', '', '', '', '', '', '', '', '', ''),
(251, 'Svalbard', 'Svalbard', '', '', '', '', '', '', '', '', '', ''),
(252, 'Tokelau', 'Tokelau', '', '', '', '', '', '', '', '', '', ''),
(253, 'Wake Island', '&Icirc;le Wake', '', '', '', '', '', '', '', '', '', ''),
(254, 'United States Pacific Island Wildlife Refuges', 'United States Pacific Island Wildlife Refuges', '', '', '', '', '', '', '', '', '', ''),
(255, 'Hawaii', 'Hawa&iuml;', '', '', '', '', '', '', '', '', '', '');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `country`
--
ALTER TABLE `country`
  ADD PRIMARY KEY (`idCountry`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `country`
--
ALTER TABLE `country`
  MODIFY `idCountry` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=256;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
